# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanbiao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='key',
            new_name='key_value',
        ),
    ]
