# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanbiao', '0006_auto_20181112_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='epos',
            name='yq',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
