# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanbiao', '0007_epos_yq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epos',
            name='img',
        ),
        migrations.RemoveField(
            model_name='epos',
            name='key_value',
        ),
    ]
